### ISSUE TITLE
Warning: KernelRestarter: restart failed

### ISSUE THREAD

**Issue by pylang** [takluyver/r2_kernel#3]
I'm trying r2_kernel due to issues getting IR_kernel to work on my Win7 machine.  I tried installing setup.py and got this:

```
C:\Anaconda\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build\lib
creating build\lib\r2_kernel
copying r2_kernel\kernel.py -> build\lib\r2_kernel
copying r2_kernel\__init__.py -> build\lib\r2_kernel
copying r2_kernel\__main__.py -> build\lib\r2_kernel
copying r2_kernel\init.r -> build\lib\r2_kernel
running install_lib
creating C:\Anaconda\Lib\site-packages\r2_kernel
copying build\lib\r2_kernel\init.r -> C:\Anaconda\Lib\site-packages\r2_kernel
copying build\lib\r2_kernel\kernel.py -> C:\Anaconda\Lib\site-packages\r2_kernel

copying build\lib\r2_kernel\__init__.py -> C:\Anaconda\Lib\site-packages\r2_kern
el
copying build\lib\r2_kernel\__main__.py -> C:\Anaconda\Lib\site-packages\r2_kern
el
byte-compiling C:\Anaconda\Lib\site-packages\r2_kernel\kernel.py to kernel.pyc
  File "C:\Anaconda\Lib\site-packages\r2_kernel\kernel.py", line 76
    print(self.error, file=sys.__stdout__)
                          ^
SyntaxError: invalid syntax

byte-compiling C:\Anaconda\Lib\site-packages\r2_kernel\__init__.py to __init__.p
yc
byte-compiling C:\Anaconda\Lib\site-packages\r2_kernel\__main__.py to __main__.p
yc
running install_egg_info
Writing C:\Anaconda\Lib\site-packages\r2_kernel-0.1-py2.7.egg-info
Installing IPython kernel spec
```

Running `ipython qtconsole --kernel r2` gives me a popup kernel that fails to start.

[Win7, python 2 default, IPython3, R.3.1.2, rpy2 installed]

**Comment by takluyver** [comment]
It was some leftover debugging code that wasn't compatible with Python 2. I've removed it, but I've been testing with Python 3, so it might not work completely with Python 2. If you encounter more problems, try creating a Python 3 env in anaconda by doing `conda create -n py3env python=3`.

**Comment by pylang** [comment]
Thanks.  I have Py3 env set up, but I can't figure how to default to Py3 besides `ipython notebook` within my Py3 folder.  I want to start from my Anaconda shortcut in IPy3 with access to py2, py3 and R kernels.  I only have py2 showing up.

**Comment by takluyver** [comment]
To expose a Python 3 kernel to the IPython that the Anaconda shortcut starts, run `ipython kernelspec install-self --user` in your Py3 env.

With the Py3 env active, try installing r2_kernel with `pip install r2_kernel --user`.

**Comment by pylang** [comment]
Thanks.  Your first bit of advice worked.  The Py3 kernel update seems to work well with my default Py2 kernel so far :+1: 

I almost got r2_kernel to work, but I got a path error trying `pip install rpy2` in my new py3k env.  I spent time trying to resolve it to no avail.  [Anaconda's advice](http://continuum.io/blog/anaconda-python-3) on `source activate py3k` does not work on Windows.  I can drop `source` and use `activate py3k` to get Py3 working, but that raises "Error: Tried to find R's HOME, but no R command in the PATH", despite  R and `rpy2` working fine in Py2.  Any tips for resolving path issues for Anaconda-Windows users?

[Win7, Py2 (default), Py3 (virtenv), IPy3]

**Comment by takluyver** [comment]
I know rpy2 has had various installation issues on Windows. You may be able to help it by setting the R_HOME environment variable to the path containing R before installing. People on the rpy2 mailing lists might be able to help you more.

**Comment by pylang** [comment]
**SOLVED**  Tried again. This time everything worked :+1:   For anyone with related problems, here's what I did for reference:

For those running IPython 3 using python 2 through Anaconda, you can install a python 3 virtualenv using instructions from [their site](http://continuum.io/blog/anaconda-python-3).

To install the r2_kernel, follow these instructions from @takluyver a few comments above: 

> To expose a Python 3 kernel to the IPython that the Anaconda shortcut starts, run `ipython kernelspec install-self --user` in your Py3 env.
> 
> With the Py3 env active, try installing r2_kernel with `pip install r2_kernel --user`.

On Windows 7, you may experience some path- and installation-related errors in conda.  Try to install `rpy2` followed by `singledispatch` within your py3k virtualenv:
1. Download the appropriate binary from [Dr. Gohlke's page](http://www.lfd.uci.edu/~gohlke/pythonlibs/#rpy2).  Install by running `pip install rpy2-2.5.6-cp33-none-win_amd64.whl` (use your rpy2 version).
2. Run `pip install singledispatch` (helped resolve import errors in python 3 and the r2_kernel from crashing).

I successfully got an R kernel option in my dropdown menu, and I confirmed r2_kernel worked using straight R code, i.e. the following plotted as expected: 

```
X <- c(0,1,2,3,4)
Y <- c(3,5,4,6,7)
XYlm = lm(Y~X)
XYcoef = coef(XYlm)
print(summary(XYlm))
s <- capture.output({summary(XYlm)})
par(mfrow=c(2,2))
plot(XYlm)
```

_Caution_: Executing cells at present flashes an R popup window before rendering in the notebook. 

It works well aside.  Personally, compared to appending `%%R` to every cell and hacking around rpy2, this kernel is a great improvement. Thanks to @takluyver for his work!

[Win7, Python 2 (default), IPython3, py3k (virtualenv), R-3.1.2, rpy2-2.5.6-cp33-none-win_amd64]

**Comment by takluyver** [comment]
Excellent, glad you got it working, and thanks for describing in detail what you've done.

Ping @davclark - the info in the comment above may be useful when we look into better Windows support for rpy2.
