### ISSUE TITLE
playing dplyr vignette, the integrated help cannot be displayed

### ISSUE THREAD

**Issue by stonebig** [takluyver/r2_kernel#4]
hi,

I have a problem

```
library("dplyr")
?select
```

doesn't succeed to launch the help on select (a new webserver starts, than display nothing)
(it works better on tmpnb.org)

**Comment by stonebig** [comment]
oups ! my fault

**Comment by takluyver** [comment]
In general, if you close one issue and want to ask about something else, you can just open another issue rather than reopening it and changing the content.

Yes, at present there's no integation with the help system. We need to set the 'pager' option in R.
