### ISSUE TITLE
I can't use R in Jupyter Notebook

### ISSUE THREAD

**Issue by weisskatze** [takluyver/r2_kernel#5]
When I open a new page for R in Jupyter Notebook, some error occurs.
I already removed and reinstalled Anaconda and R, but it didn't work.
What can I do?

< Error message >
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=b9869131c9496bc017ea44691060e68b72a0a4ec147c07db
[I 21:09:35.747 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 21:09:49.828 NotebookApp] Creating new notebook in
[I 21:09:51.898 NotebookApp] Kernel started: 7f67ee12-fdea-447f-b008-3fe07e2c910b
: package or namespace load failed for 'RevoUtilsMath':
 .onLoad loadNamespace() 'RevoUtilsMath' :
  : NULL
  : Remove Microsoft R using Add/Remove Programs, then re-install.
Be sure to select MKL as an install option.

[I 21:09:54.884 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
: package or namespace load failed for 'RevoUtilsMath':
 .onLoad loadNamespace() 'RevoUtilsMath' :
  : NULL
  : Remove Microsoft R using Add/Remove Programs, then re-install.
Be sure to select MKL as an install option.

[I 21:09:57.892 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
: package or namespace load failed for 'RevoUtilsMath':
 .onLoad loadNamespace() 'RevoUtilsMath' :
  : NULL
  : Remove Microsoft R using Add/Remove Programs, then re-install.
Be sure to select MKL as an install option.

[I 21:10:00.919 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
: package or namespace load failed for 'RevoUtilsMath':
 .onLoad loadNamespace() 'RevoUtilsMath' :
  : NULL
  : Remove Microsoft R using Add/Remove Programs, then re-install.
Be sure to select MKL as an install option.

[I 21:10:03.940 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
: package or namespace load failed for 'RevoUtilsMath':
 .onLoad loadNamespace() 'RevoUtilsMath' :
  : NULL
  : Remove Microsoft R using Add/Remove Programs, then re-install.
Be sure to select MKL as an install option.

[W 21:10:06.957 NotebookApp] KernelRestarter: restart failed
[W 21:10:06.957 NotebookApp] Kernel 7f67ee12-fdea-447f-b008-3fe07e2c910b died, removing from map.
[I 21:10:15.304 NotebookApp] Interrupted...
[I 21:10:15.304 NotebookApp] Shutting down 0 kernels

**Comment by takluyver** [comment]
Hi, this repo hasn't had any activity in years. You probably want either [IRkernel](https://github.com/IRkernel/IRkernel) or [JuniperKernel](https://github.com/JuniperKernel/JuniperKernel/).
